services:
  scell.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: scell.analysis.unite.net
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.analysis.scell

networks:
  default:
    name: unite
    external: true
