services:
  analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: analysis.unite.net
    build: 
      context: ./src
      dockerfile: ./Dockerfile
      args: 
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.analysis

networks: 
  default:
    name: unite
    external: true
