services:
  pcam.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: pcam.analysis.unite.net
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.analysis.pcam

networks:
  default:
    name: unite
    external: true
