services:
  pgsql.unite.net:
    image: postgres
    shm_size: 256m
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      # - ./data:/var/lib/postgresql/data
      # - pgsql.data:/var/lib/postgresql/data:rw
      - pgsql.data:/var/lib/postgresql:rw
    ports:
      - 127.0.0.1:5432:5432

networks: 
  default:
    name: unite
    external: true

volumes:
  pgsql.data:
    name: pgsql.data
    driver: local
