services:
  es.unite.net:
    image: elasticsearch:7.17.7
    container_name: es
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${PASSWORD}
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - ingest.geoip.downloader.enabled=false
    volumes:
      - es.data:/usr/share/elasticsearch/data:rw
    ports:
      - 127.0.0.1:9200:9200

networks: 
  default:
    name: unite
    external: true

volumes:
  es.data:
    name: es.data
    driver: local
